### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by daspliff** [arifwn/AERMOD-linux#1]
I tried to compile the program and got the following error:

gfortran -c -fcheck=bounds -O2 -mtune=native modules.f -o modules.o
f951: error: unrecognized command line option "-fcheck=bounds"
make: **\* [modules.o] Error 1

I commented out the option in the makefile and the program compiled successfully. Can you comment on  how the omission impacts the program?

**Comment by arifwn** [comment]
-fcheck=bounds is used to enable index out-of-bound checking. If omitted, instead of crashing when index-out-of-bound happen while accessing an array, the program might still continue with the corrupted data. But I think it shouldn't have any meaningful impact in aermod (I never encounter any array-related crash when I was using aermod a while ago).

**Comment by daspliff** [comment]
Hey arifwn,

So I used your  code previously (over the last year) to compile an older version of Aermod and it worked superbly. However, EPA recently released a newer version of Aermod and I wanted to upgrade. So I modified your makefile and compiled the Aermet v15181 and Aermod v15181. Everything compiled fine. The new version of Aermet works fine. However, the new version of AERMOD (v15181) segfaults on execution with the following error:

+Now Processing SETUP Information 

Program received signal SIGSEGV: Segmentation fault - invalid memory reference. 

Backtrace for this error: 
#0 0x2B1EFA7C7B47 
#1 0x2B1EFA7C6D40 
#2 0x3AC9C3269F 
#3 0x43B6D4 in varini_ 
#4 0x42B346 in MAIN__ at aermod.f:0 
Segmentation fault 

Can you shed any light on what might be the issue here? I am using gfortran with gcc v5.1.0. Have you succesfilly compiled Aermod v15181. Can you gave it a try and see of you get this error? Thanks in advance

**Comment by arifwn** [comment]
Hmm, apparently if you delete line 1636-1639 on setup.f in aermod source code (the latest version (v15181) on epa.gov), the resulting binary can run the sample data without crashing ( http://www.epa.gov/ttn/scram/models/aermod/SampleRun.zip ), but I'm not sure about the validity of the results.

Use the following makefile to turn on debugging: 

```
FC=gfortran
FCFLAGS=-c -fcheck=all -Wall -g -fbacktrace -O2 -mtune=native 
LDFLAGS=

OBJECTS=modules.o aermod.o setup.o coset.o soset.o reset.o meset.o ouset.o inpsum.o metext.o iblval.o siggrid.o tempgrid.o windgrid.o calc1.o calc2.o prise.o prime.o sigmas.o pitarea.o output.o evset.o evcalc.o evoutput.o

all: $(OBJECTS)
    $(FC) $(LDFLAGS) $(OBJECTS) -o aermod

%.o: %.f
    $(FC) $(FCFLAGS) $< -o $@

clean:
    rm -rf *.o *.mod *.exe aermod
```

I'll look into it more later.

**Comment by daspliff** [comment]
So I got around this issue by using the latest Intel Fortran compiler. It compiles fine and executes without issue. I am mobile right now. I will post makefile later.
